---
  - name: "Create zookeeper directory"
    file:
      path: "{{item}}"
      owner: root
      mode: 0755
      state: directory
    with_items: 
    - '/etc/kafka'
    - '/var/lib/zookeeper'
    tags: zookeeper_config
    when: "'zookeeper' in group_names"

  - name: create  file
    file:
      path: "/var/lib/zookeeper/myid"
      owner: root
      state: touch
    tags: zookeeper_config
    when: "'zookeeper' in group_names"


  - name: "Zookeeper configuration"
    template:
     src:  "{{item.src}}"
     dest: "{{item.dest}}"
     owner: root
     group: root
     mode: 0655
    with_items:
    - { src: 'zookeeper.properties.j2',dest: '/etc/kafka/zookeeper.properties'}
    - { src: 'myid.j2' ,dest: '/var/lib/zookeeper/myid'}
    tags: zookeeper_config
    when: "'zookeeper' in group_names"


  


   


